# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        # -v: verbose
        # -z: compress files during transfer
        # -r: copy files recursively
        # --delete: delete extraneous files from dest dirs
        switches: -vzr --delete
        remote_path: /var/www/larryyoung.dev
        remote_host: 34.125.50.127
        remote_user: github
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - run: npm i
    - run: npm run build --if-present
